cloud:
  aws:
    credentials:
      access-key: AKIAXXTFF2PMREK7FGTT
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: encare
  security:
    secret-key: iamsixblack

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080