cloud:
  aws:
    credentials:
      access-key: AKIAULKD23ZB3UUMJQD3
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: nts-sixblack-hexa
  security:
    secret-key: sixblack



spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090


